using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media.Imaging;
using RMX3171ControlCentre.Models.Storage;
using RMX3171ControlCentre.Services.Adb;

namespace RMX3171ControlCentre.ViewModels.Storage
{
    public class VideoThumbnailLoader : IDisposable
    {
        private readonly IAdbService _adbService;
        private readonly string _cacheDir;
        
        // Bounded memory cache: mapping ID to BitmapImage
        private readonly ConcurrentDictionary<string, BitmapImage> _memoryCache = new();
        private readonly Queue<string> _cacheOrder = new();
        private const int MaxCacheSize = 300;

        private readonly SemaphoreSlim _concurrencyLimiter = new(4, 4);
        private readonly Dictionary<VideoItem, CancellationTokenSource> _pendingTasks = new();
        
        public VideoThumbnailLoader(IAdbService adbService)
        {
            _adbService = adbService;
            _cacheDir = Path.Combine(Path.GetTempPath(), "RMX3171_VideoThumbnails");
            if (!Directory.Exists(_cacheDir))
            {
                Directory.CreateDirectory(_cacheDir);
            }
        }

        public void RequestThumbnail(VideoItem item)
        {
            if (item == null || string.IsNullOrWhiteSpace(item.Id)) return;

            // Already cached?
            if (_memoryCache.TryGetValue(item.Id, out var bmp))
            {
                item.Thumbnail = bmp;
                return;
            }

            // Already pending?
            if (_pendingTasks.ContainsKey(item)) return;

            var cts = new CancellationTokenSource();
            _pendingTasks[item] = cts;

            _ = LoadThumbnailAsync(item, cts.Token);
        }

        private async Task LoadThumbnailAsync(VideoItem item, CancellationToken token)
        {
            await _concurrencyLimiter.WaitAsync(token);
            string tempFileName = Guid.NewGuid().ToString("N") + ".jpg";
            string localPath = Path.Combine(_cacheDir, tempFileName);
            
            try
            {
                token.ThrowIfCancellationRequested();
                
                // Read the thumbnail generated by Android's MediaStore directly!
                var readCmd = $"shell \"content read --uri content://media/external/video/media/{item.Id}/thumbnail > /data/local/tmp/{tempFileName}\"";
                await _adbService.ExecuteCommandAsync(readCmd, true, token);

                token.ThrowIfCancellationRequested();

                var pullCmd = $"pull \"/data/local/tmp/{tempFileName}\" \"{localPath}\"";
                await _adbService.ExecuteCommandAsync(pullCmd, true, token);

                // Clean up device temp
                _ = _adbService.ExecuteCommandAsync($"shell rm /data/local/tmp/{tempFileName}", true, CancellationToken.None);

                token.ThrowIfCancellationRequested();

                if (File.Exists(localPath) && new FileInfo(localPath).Length > 0)
                {
                    BitmapImage? bmp = null;
                    await Application.Current.Dispatcher.InvokeAsync(() =>
                    {
                        try
                        {
                            bmp = new BitmapImage();
                            bmp.BeginInit();
                            bmp.CacheOption = BitmapCacheOption.OnLoad;
                            bmp.CreateOptions = BitmapCreateOptions.IgnoreColorProfile;
                            bmp.UriSource = new Uri(localPath);
                            bmp.EndInit();
                            bmp.Freeze();
                        }
                        catch
                        {
                            bmp = null;
                        }
                    });

                    if (bmp != null)
                    {
                        ManageCache(item.Id, bmp);
                        if (!token.IsCancellationRequested)
                        {
                            item.Thumbnail = bmp;
                        }
                    }
                }
            }
            catch (OperationCanceledException)
            {
                // Expected
            }
            catch (Exception)
            {
                // Suppress and fallback to null (empty UI container)
            }
            finally
            {
                _concurrencyLimiter.Release();
                _pendingTasks.Remove(item);
                try { if (File.Exists(localPath)) File.Delete(localPath); } catch { }
            }
        }

        public void CancelRequest(VideoItem item)
        {
            if (_pendingTasks.TryGetValue(item, out var cts))
            {
                cts.Cancel();
                _pendingTasks.Remove(item);
            }
        }

        private void ManageCache(string id, BitmapImage bmp)
        {
            if (_memoryCache.TryAdd(id, bmp))
            {
                _cacheOrder.Enqueue(id);
                if (_cacheOrder.Count > MaxCacheSize)
                {
                    // Evict half to avoid constant trimming
                    int toRemove = MaxCacheSize / 2;
                    for (int i = 0; i < toRemove; i++)
                    {
                        if (_cacheOrder.TryDequeue(out var oldId))
                        {
                            _memoryCache.TryRemove(oldId, out _);
                        }
                    }
                }
            }
        }

        public void Clear()
        {
            foreach (var cts in _pendingTasks.Values)
            {
                cts.Cancel();
            }
            _pendingTasks.Clear();
            _memoryCache.Clear();
            _cacheOrder.Clear();
            
            try
            {
                if (Directory.Exists(_cacheDir))
                {
                    foreach (var file in Directory.GetFiles(_cacheDir))
                    {
                        try { File.Delete(file); } catch { }
                    }
                }
            }
            catch { }
        }

        public void Dispose()
        {
            Clear();
            _concurrencyLimiter.Dispose();
        }
    }
}
